# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-25 11:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_floors', models.IntegerField(default=1)),
                ('base_floor', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=220, null=True)),
                ('type', models.CharField(blank=True, choices=[('img', 'Image'), ('vid', 'Video')], max_length=3, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Nearest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('distance', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Overlooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('contact', models.IntegerField()),
                ('role', models.CharField(choices=[(1, 'Owner'), (2, 'Agent'), (3, 'Customer')], default=1, max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='property_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='category',
        ),
        migrations.RemoveField(
            model_name='property',
            name='nearest_landmarks',
        ),
        migrations.RemoveField(
            model_name='property',
            name='type',
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='a_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='beam_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='buildup_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cafeteria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='carpet_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='ceiling_details',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ceiling_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='earthing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='electrical_con',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='facing',
            field=models.CharField(blank=True, choices=[('n', 'North'), ('ne', 'North East'), ('nw', 'North West'), ('s', 'South'), ('se', 'South East'), ('sw', 'South west'), ('e', 'East'), ('w', 'West')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='fire_sprinklers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='flooring',
            field=models.CharField(blank=True, choices=[('tile', 'Tiles'), ('wood', 'Wooden'), ('carpet', 'Carpet'), ('bare', 'Bare')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='flooring_details',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(blank=True, choices=[('semi', 'Semi Furnished'), ('bare', 'Bareshell')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='landmark',
            field=models.ManyToManyField(blank=True, to='buyproperty.Landmark'),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_term',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lift_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_maintenance',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_basements',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pantry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.CharField(blank=True, choices=[('cover', 'Covered'), ('expose', 'Exposed')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='power_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='property_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_number_of_floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_of_area',
            field=models.CharField(blank=True, choices=[('sqmt', 'Square Mt.'), ('sqft', 'Square Ft.')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='units_on_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='washroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='washroom_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyproperty.Address'),
        ),
        migrations.AddField(
            model_name='property',
            name='media',
            field=models.ManyToManyField(blank=True, to='buyproperty.Media'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest',
            field=models.ManyToManyField(blank=True, to='buyproperty.Nearest'),
        ),
        migrations.AddField(
            model_name='property',
            name='other_charges',
            field=models.ManyToManyField(blank=True, to='buyproperty.OtherCharges'),
        ),
        migrations.AddField(
            model_name='property',
            name='overlooking',
            field=models.ManyToManyField(blank=True, to='buyproperty.Overlooking'),
        ),
    ]
