# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-30 08:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='other_charges',
        ),
        migrations.AddField(
            model_name='property',
            name='other_charges',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
