# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-30 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0002_auto_20181030_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='landmark',
        ),
        migrations.AddField(
            model_name='property',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Landmark',
        ),
    ]
