# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-25 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0002_auto_20181025_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='property',
            name='number_of_basements',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_of_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='units_on_floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
