# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-30 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0003_auto_20181030_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='overlooking',
        ),
        migrations.AddField(
            model_name='property',
            name='overlooking',
            field=models.CharField(blank=True, choices=[('w', 'Water Body'), ('g', 'Garden'), ('r', 'Road')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Overlooking',
        ),
    ]
