# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-30 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0004_auto_20181030_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overlooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='overlooking',
        ),
        migrations.AddField(
            model_name='property',
            name='overlooking',
            field=models.ManyToManyField(blank=True, to='buyproperty.Overlooking'),
        ),
    ]
