# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-25 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0005_auto_20181025_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearest',
            name='title',
            field=models.CharField(blank=True, choices=[('bus', 'Bus Stop'), ('school', 'School'), ('mall', 'Shopping Mall'), ('hospital', 'Hospital'), ('bank', 'Bank'), ('atm', 'ATM'), ('restaurant', 'Restaurant'), ('metro', 'Metro Station'), ('train', 'Train Station'), ('pharmacy', 'Pharmacy')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='ceiling_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='flooring_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lease_term',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
