# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-31 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0007_property_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='default_in_group',
            field=models.BooleanField(default=False),
        ),
    ]
