# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-29 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0007_auto_20181028_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
