# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-01 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0008_media_default_in_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_video_tour', to='buyproperty.Media'),
        ),
    ]
