# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-01 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0009_property_video_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplan',
            name='base_floor',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='number_of_floors',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='floor_number',
            field=models.IntegerField(blank=True, choices=[(0, 'GROUND'), (1, 'FIRST'), (2, 'SECOND'), (3, 'THIRD')], null=True),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='media',
            field=models.ManyToManyField(blank=True, null=True, to='buyproperty.Media'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_plan',
            field=models.ManyToManyField(blank=True, to='buyproperty.FloorPlan'),
        ),
    ]
