# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-01 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0010_auto_20181101_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='media',
            field=models.ManyToManyField(blank=True, to='buyproperty.Media'),
        ),
    ]
