# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-01 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0011_auto_20181101_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, choices=[('b', 'Banner'), ('t', 'Tour')], max_length=1, null=True)),
                ('url', models.URLField(blank=True, max_length=350, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(blank=True, choices=[('b', 'Banner'), ('f', 'Floor Plan')], max_length=1, null=True),
        ),
    ]
