# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-01 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0012_auto_20181101_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floorplan',
            old_name='media',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='media',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='property',
            name='video_tour',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='videos',
            field=models.ManyToManyField(blank=True, to='buyproperty.Video'),
        ),
        migrations.AddField(
            model_name='property',
            name='videos',
            field=models.ManyToManyField(blank=True, to='buyproperty.Video'),
        ),
    ]
