# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-02 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0013_auto_20181101_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
