# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-01 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0013_auto_20181101_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
