# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-02 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0014_auto_20181102_0648'),
        ('buyproperty', '0015_auto_20181101_1454'),
    ]

    operations = [
    ]
