# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-02 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0016_merge_20181102_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='description',
            field=models.TextField(blank=True, default='Floor description here'),
        ),
    ]
