# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-02 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0019_auto_20181102_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlead',
            name='contact',
            field=models.CharField(blank=True, default=' ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='agentlead',
            name='email',
            field=models.EmailField(blank=True, default='someone@example.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='agentlead',
            name='name',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AlterField(
            model_name='customerlead',
            name='contact',
            field=models.CharField(blank=True, default=' ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerlead',
            name='name',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AlterField(
            model_name='property',
            name='contact',
            field=models.CharField(blank=True, default=' ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='landmark',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(blank=True, default=' ', max_length=250),
        ),
    ]
