# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-02 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0020_auto_20181102_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='othercharges',
            options={'verbose_name': 'Other Charge', 'verbose_name_plural': 'Other Charges'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
