# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-12 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0023_auto_20181112_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='map_address',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
