# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-20 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0025_bannersetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='number_of_floors',
            new_name='floor_number',
        ),
    ]
