# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-20 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0026_auto_20181120_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='number_of_floor',
            field=models.IntegerField(default=1, help_text='floor number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='floor_number',
            field=models.IntegerField(blank=True, choices=[(-1, 'No Plan'), (0, 'Bareshell layout'), (1, 'Design Option 1'), (2, 'Design Option 2'), (3, 'Design Option 3')], help_text='floor plan', null=True),
        ),
    ]
