# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-20 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0028_testimonialsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlead',
            name='partner_type',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('builder', 'Builder'), ('broker', 'Broker'), ('client', 'Client')], max_length=10, null=True),
        ),
    ]
