# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-20 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0029_customerlead_partner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialsetting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
