# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-23 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0031_nearest_nearest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='floor_number',
            field=models.IntegerField(blank=True, choices=[(-1, 'No Plan'), (0, 'Bareshell layout'), (1, 'Office Plan'), (2, 'Design Renders'), (3, 'Site Photos')], help_text='floor plan', null=True),
        ),
    ]
