# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-29 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0035_auto_20181126_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlead',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
