# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-01 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0036_customerlead_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='security_deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
